### ISSUE TITLE
Editor Crashes After Adding New Sprites

### ISSUE THREAD

**Issue by jessidion** [AscensionGameDev/Intersect-Engine#1085]
**Describe the bug**
I added Entities and paperdolls but now the editor keep crashing when clickling on most Game Editor windows.

**Version Encountered**

0.7.0.129
**To Reproduce**
1. Open Editor
2. Go to Game Editors
3. Click on Class Editor, Item Editor or NPC editor
4. Editor Crashes

**Expected behavior**
I expected the editor not to crash after adding new sprites...

**Screenshots**

**Logs**
If there are error logs please attach them below.
2022-02-24 18:55:04.651 [Error] 
  Message: Failed to compare two elements in the array.
    Stack:    at System.Array.SorterObjectArray.IntrospectiveSort(Int32 left, Int32 length)
   at System.Array.Sort(Array keys, Array items, Int32 index, Int32 length, IComparer comparer)
   at System.Array.Sort(Array array, IComparer comparer)
   at Intersect.Editor.Content.GameContentManager.SmartSort(String[] strings) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Content\ContentManager.cs:line 600
   at Intersect.Editor.Content.GameContentManager.GetSmartSortedTextureNames(TextureType type) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Content\ContentManager.cs:line 527
   at Intersect.Editor.Forms.Editors.FrmClass.frmClass_Load(Object sender, EventArgs e) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\frmClass.cs:line 285
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Caused By
  Message: Value was either too large or too small for an Int32.
    Stack:    at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at Intersect.Utilities.AlphanumComparator.Compare(Object x, Object y) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect (Core)\Utilities\AlphanumComparator.cs:line 109
   at System.Array.SorterObjectArray.PickPivotAndPartition(Int32 lo, Int32 hi)
   at System.Array.SorterObjectArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterObjectArray.IntrospectiveSort(Int32 left, Int32 length)

--------------------------------------------------------------------------------

**Operating System:**
Windows 10 Pro

**Additional context**

**Comment by Arufonsu** [comment]
An integer (Int32) is limited in the values it can store since it "only" uses 32 bits. It can store a value between 2,147,483,647 and -2,147,483,648. The value represented by your sprite names is probably too large or too small? mind telling us the names used? and if you used whitespacing on the sprite names?

Also, i probably misunderstood the logs but, shouldn't we prefer Int32.TryParse instead of Convert.ToInt32 when the source value is a string?

**Comment by Arufonsu** [comment]
An integer (Int32) is limited in the values it can store since it only uses 32 bits. It can store a value between 2,147,483,647 and -2,147,483,648. The value represented by your sprite names is probably too large or too small? mind telling us the names used? and if you used whitespacing on the sprite names?

Also, (a question to maintainers and collaborators): i probably misunderstood the logs but, shouldn't we prefer Int32.TryParse instead of Convert.ToInt32 when the source value is a string?

**Comment by jessidion** [comment]
> 

I forgot to come back and mark this as solved. Thank you, you are right as well. I got the hint from the logs and checked my sprite names, in fact they had a pretty long name (like "2123qa5sda6ad8f-1_attack") and this was the cause. I had to use a bulk rename program as I had over 2000 files to rename and it was a pain. Thanks :)
