### ISSUE TITLE
MapGrids crashing pathfinding/map packet generation when saving maps

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#130]
**Describe the bug**
Pathfinding errors and map packet generation errors when MapGrids are being regenerated.

**Version Encountered**
0.6.2.410

**To Reproduce**
Half a lot of maps, a slow server, some players online, and save maps until it happens XD

**Expected behavior**
Accessing the MapGrid list should never crash. We should make it private, and add a function to access a MapGrid by index, or turn it into a concurrentdictionary.

**Screenshots**
N/A

**Logs**
```
--------------------------------------------------------------------------------
2020-04-12 19:20:49.021 [Error] 
  Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Intersect.Server.Entities.Pathfinding.Pathfinder.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Pathfinding\Pathfinder.cs:line 145


--------------------------------------------------------------------------------
2020-04-12 19:20:49.052 [Error] 
  Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Intersect.Server.Entities.Pathfinding.Pathfinder.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Pathfinding\Pathfinder.cs:line 88

--------------------------------------------------------------------------------
2020-04-12 19:25:48.646 [Error] 
  Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Intersect.Server.Networking.PacketSender.GenerateMapPacket(Client client, Guid mapId) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Networking\PacketSender.cs:line 171
   at Intersect.Server.Networking.PacketSender.SendAreaPacket(Player player) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Networking\PacketSender.cs:line 122
   at Intersect.Server.Networking.PacketSender.SendMapGrid(Client client, Int32 gridIndex, Boolean clearKnownMaps) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Networking\PacketSender.cs:line 1116
   at Intersect.Server.Entities.Player.Warp(Guid newMapId, Byte newX, Byte newY, Byte newDir, Boolean adminWarp, Byte zOverride, Boolean mapSave) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Player.cs:line 1311
   at Intersect.Server.Entities.Events.CommandProcessing.ProcessCommand(WarpCommand command, Player player, Event instance, CommandInstance stackInfo, Stack`1 callStack) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Events\CommandProcessing.cs:line 608
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Intersect.Server.Entities.Events.CommandProcessing.ProcessCommand(EventCommand command, Player player, Event instance) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Events\CommandProcessing.cs:line 33
   at Intersect.Server.Entities.Events.Event.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Events\Event.cs:line 204
   at Intersect.Server.Entities.Player.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Player.cs:line 500
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Maps\MapInstance.cs:line 804
   at Intersect.Server.Core.ServerLoop.RunServerLoop() in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Core\ServerLoop.cs:line 38
```

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by jcsnider** [comment]
Also crashing TileHelper
```
2020-04-12 19:35:44.054 [Error] 
  Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Intersect.Server.Maps.TileHelper.TransitionMaps(Int32 direction) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Maps\TileHelper.cs:line 115
   at Intersect.Server.Maps.TileHelper.Fix() in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Maps\TileHelper.cs:line 156
   at Intersect.Server.Maps.TileHelper.TryFix() in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Maps\TileHelper.cs:line 50
   at Intersect.Server.Maps.TileHelper.Translate(Int32 xOffset, Int32 yOffset) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Maps\TileHelper.cs:line 43
   at Intersect.Server.Entities.Entity.CanMove(Int32 moveDir) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Entity.cs:line 326
   at Intersect.Server.Entities.Npc.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Entities\Npc.cs:line 931
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs) in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Maps\MapInstance.cs:line 804
   at Intersect.Server.Core.ServerLoop.RunServerLoop() in C:\Users\Administrator\Desktop\Intersect-Engine\Intersect.Server\Core\ServerLoop.cs:line 38
```
