### ISSUE TITLE
Strange Crash from Heal Spell

### ISSUE THREAD

**Issue by rhathaway86** [AscensionGameDev/Intersect-Engine#154]
**Describe the bug**
Once and a while (not very often, it has only happened twice and is very hard to replicate), when using a heal spell the server will crash. This is not a buff/status effect spell, simply a targeted heal spell.

**Version Encountered**
Current Dev

**To Reproduce**
Hard to reproduce, just randomly happens from nowhere.

**Expected behavior**
No crashing/not treating spell like a buff? Its not a buff spell, but is crashing on the en.Statuses.Add(Spell, this); line.

**Screenshots**

**Logs**
2020-04-18 03:19:03.998 [Error] Received unhandled exception from .

--------------------------------------------------------------------------------
2020-04-18 03:19:04.002 [Error] 
  Message: Object reference not set to an instance of an object.
    Stack:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Intersect.Server.Entities.Combat.Status..ctor(Entity en, SpellBase spell, StatusTypes type, Int32 duration, String data) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Entities\Combat\Status.cs:line 86
   at Intersect.Server.Entities.Entity.TryAttack(Entity target, SpellBase spellBase, Boolean onHitTrigger, Boolean trapTrigger) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Entities\Entity.cs:line 1546
   at Intersect.Server.Entities.Entity.CastSpell(Guid spellId, Int32 spellSlot) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Entities\Entity.cs:line 2057
   at Intersect.Server.Entities.Player.CastSpell(Guid spellId, Int32 spellSlot) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Entities\Player.cs:line 4095
   at Intersect.Server.Entities.Entity.Update(Int64 timeMs) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Entities\Entity.cs:line 240
   at Intersect.Server.Entities.Player.Update(Int64 timeMs) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Entities\Player.cs:line 369
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Maps\MapInstance.cs:line 807
   at Intersect.Server.Core.ServerLoop.RunServerLoop() in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Core\ServerLoop.cs:line 38

--------------------------------------------------------------------------------
2020-04-18 03:19:25.055 [Error] Received unhandled exception from Name:Intersect Server.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2020-04-18 03:19:25.055 [Error] 
  Message: Object reference not set to an instance of an object.
    Stack:    at Intersect.Server.Core.Bootstrapper.ConsoleCtrlCheck(CtrlTypes ctrlType) in C:\Users\August\Documents\GitHub\Intersect-Engine\Intersect.Server\Core\Bootstrapper.cs:line 538

--------------------------------------------------------------------------------

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by rhathaway86** [comment]
Hm, I may have found the issue was on my end. I was doing a check on the target for statuses and did not save them target.Statuses.ToArray();  to an array.
