### ISSUE TITLE
bug: crash at clicked login

### ISSUE THREAD

**Issue by darkjezza** [AscensionGameDev/Intersect-Engine#1795]
### Description

changing ip to public ip then clicking login crashes the game i left a log that has the error

### Steps to Reproduce

1. change ip to your public ip
2. press login
3. should crash

### Version with bug

v0.7.2-beta.7

### Last version that worked well

Unkown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

no

### Relevant log output

```shell
2023-04-27 09:04:18.548 [Info] Discovered 0 plugins:


--------------------------------------------------------------------------------
2023-04-27 09:04:19.739 [Info] Connecting to masked:5400...

--------------------------------------------------------------------------------
2023-04-27 09:04:20.338 [Info] Connection approved [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2023-04-27 09:04:20.402 [Info] Connected [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2023-04-27 09:04:22.258 [Info] Acquiring context lock... (0ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.260 [Info] Acquired. (1ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.262 [Info] Beginning context dispose. (0ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.262 [Info] GC.SuppressFinalize (0ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.262 [Info] InternalDispose() completed. (0ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.262 [Info] Clearing instance... (3ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.262 [Info] Releasing context lock... (3ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.262 [Info] Released. (3ms)

--------------------------------------------------------------------------------
2023-04-27 09:04:22.263 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Menu.LoginWindow.Show()
   at Intersect.Client.Framework.Gwen.Control.Base.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Control.Button.OnClicked(Int32 x, Int32 y)
   at Intersect.Client.Framework.Gwen.Control.Button.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Input.InputHandler.OnMouseClicked(Base canvas, Int32 mouseButton, Boolean down)
   at Intersect.Client.Framework.Gwen.Input.IntersectInput.ProcessMessage(Object message)
   at Intersect.Client.MonoGame.Input.MonoInput.CheckMouseButton(Keys modifier, ButtonState bs, MouseButtons mb)
   at Intersect.Client.MonoGame.Input.MonoInput.Update()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
_Going to assume that the server has to be up._

> 1. change ip to your public ip

i'm .. _going to assume_ that you mean the client's config so the ip that is trying to connect to is our server, right? - done


> 2\. press login

it logged in :man_shrugging: 


> 3\. should crash

Nope :man_shrugging:  unable to reproduce with the provided info.


if anyone else manages to reproduce this, please, provide a step by step video or description to do, i couldn't reproduce this with the given info so, im tagging this as unable to reproduce.

**Comment by darkjezza** [comment]
so this seems to be working on Intersect Cloud Hosting i can login the Version is 0.7.1.120
i don't know why your not getting the same results i am
it seems it does not like my pc

**Comment by Arufonsu** [comment]
> i don't know why your not getting the same results i am

probably an issue on your own end then 🤷‍♂️
