### ISSUE TITLE
bug: Server Crash when deleting live instance map

### ISSUE THREAD

**Issue by Richy1111** [AscensionGameDev/Intersect-Engine#1818]
### Description

[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/11583437/errors-Intersect.Server.log)
```
2023-05-28 01:36:13.323 [Error] Received unhandled exception from System.Threading.Thread.

--------------------------------------------------------------------------------
2023-05-28 01:36:13.323 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Server.Entities.Player.Update(Int64 timeMs)
   at Intersect.Server.Maps.MapInstance.UpdateEntities(Int64 timeMs)
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs)
   at Intersect.Server.Core.LogicService.LogicThread.UpdateMap(MapInstance mapInstance, Boolean onlyProjectiles)
```

### Steps to Reproduce

1. Create a map instance warp event on a map.
2. Stay logged on client, go to the instanced map.
3. In editor, delete instanced map.
4. Get server crash.

(PS, glad to know we can make live edits inside live instances without crashes.)

(PSS, if an instance isn't destroyed, and if entities are processed on the instance, deleting the said map should crash server also.)

### Version with bug

v7.1.119

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Fixed by #1819
