### ISSUE TITLE
bug: Server Crashes at some point when stoping active crafting

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1836]
### Description

https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/dd38644d-3008-4af1-981c-3f1907102643

credits: @naziozeno

### Steps to Reproduce

showed in video above

### Version with bug

v7.2.21

### Last version that worked well

Unknown

### Affected platforms

Windows

### Relevant log output

```shell
2023-07-11 13:30:59.755 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Server.Entities.Player.CraftItem()
   at Intersect.Server.Entities.Player.Update(Int64 timeMs)
   at Intersect.Server.Maps.MapInstance.UpdateEntities(Int64 timeMs)
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs)
   at Intersect.Server.Core.LogicService.LogicThread.UpdateMap(MapInstance mapInstance, Boolean onlyProjectiles)
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by naziozeno** [comment]
Made many tests at my game (what is the one on the video) and no more server crashing when stop the mass crafting.
