### ISSUE TITLE
bug: server crash when try to delete map

### ISSUE THREAD

**Issue by koraie112** [AscensionGameDev/Intersect-Engine#1877]
### Description

 when try to delete a map i error and server editor disconnnets

### Steps to Reproduce

create map
delete map
crash 
that's it

### Version with bug

v0.7.2-beta.35

### Last version that worked well

dont know

### Affected platforms

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
--------------------------------------------------------------------------------
2023-08-28 08:13:54.642 [Error] Client Packet Error! [Packet: MapListUpdatePacket | User: koraie | Player:  | IP 127.0.0.1]

--------------------------------------------------------------------------------
2023-08-28 08:13:54.642 [Error] {"DataKeys":0,"MessageLength":53,"StackTraceLength":415,"InnerException":false,"Source":"Intersect Server","TargetSite":"HandlePacket","TargetSiteDeclaringType":"Intersect.Server.Networking.PacketHandler","Type":"System.NullReferenceException"}

--------------------------------------------------------------------------------
2023-08-28 08:13:54.644 [Error] Client Packet Error! [Packet: MapListUpdatePacket | User: koraie | Player:  | IP 127.0.0.1]
2023-08-28 08:13:54.644 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Server.Networking.PacketHandler.HandlePacket(Client client, MapListUpdatePacket packet)
   at Intersect.Network.PacketHandlerRegistry.<>c__DisplayClass38_1`2.<CreateWeaklyTypedDelegateForMethodInfo>b__1(IPacketSender packetSender, IPacket packet)
   at Intersect.Server.Networking.PacketHandler.ProcessPacket(IPacket packet, Client client)
   at Intersect.Server.Networking.Client.HandlePackets()


--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
@koraie112 Please test the patch files from PR#1880 downloadable [directly from GitHub (if you are logged in)](https://github.com/AscensionGameDev/Intersect-Engine/suites/15623279990/artifacts/891683370) or [from the AGD forum's file host](https://www.ascensiongamedev.com/resources/filehost/9ddfff76289968977a5a4cdb30837431.zip).

**Comment by koraie112** [comment]
this issue is fixed , thankyou so much : )
