### ISSUE TITLE
Bug when opening map

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#195]
**Describe the bug**
idk

**Version Encountered**
0.6.1.255

**To Reproduce**
I'm trying to open a map so I can edit it. So...
Double-click on a map.

**Expected behavior**
Open the map so I can edit it.

**Logs**
--------------------------------------------------------------------------------
2020-05-04 12:27:09.723 [Error] 
  Message: Object reference not set to an instance of an object.
    Stack:    at Intersect.Editor.Core.Graphics.DrawLight(Int32 x, Int32 y, LightBase light, RenderTarget2D target) in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Graphics.cs:line 1917
   at Intersect.Editor.Core.Graphics.DrawLights(RenderTarget2D target) in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Graphics.cs:line 1904
   at Intersect.Editor.Core.Graphics.ClearDarknessTexture(RenderTarget2D target, Boolean screenShotting) in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Graphics.cs:line 1829
   at Intersect.Editor.Core.Graphics.Render() in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Graphics.cs:line 192
   at Intersect.Editor.Core.Main.DrawFrame() in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Main.cs:line 70
   at Intersect.Editor.Core.Main.RunFrame() in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Main.cs:line 102
   at Intersect.Editor.Core.Main.StartLoop() in C:\TeamCity\buildAgent\work\676c60f42f2551e6\Intersect.Editor\Core\Main.cs:line 50

--------------------------------------------------------------------------------

**Operating System:**
Windows 7 64x.

**Comment by WeylonSantana** [comment]
Edit: I can enter and walk for theses maps in client, events and animations working, only crash in editor.

**Comment by jcsnider** [comment]
Does the following file exist for your editor?

Editor/resources/shaders/radialgradient_editor.xnb?

**Comment by WeylonSantana** [comment]
Nop, i have to make download of this file?

**Comment by jcsnider** [comment]
It's part of the engine. It's been there for years. Editor needs it in order to draw lights. Go get it from one of the latest Intersect downloads.

**Comment by WeylonSantana** [comment]
I made @jcsnider. I downloaded the full version of version 255. Thanks. You can close.
