### ISSUE TITLE
bug: Connecting a Linux server with Windows

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#1952]
### Description

I've already checked a few things, unfortunately none of them work.
First, I uploaded the server version compiled on VPS Linux.
I launched it and tried to log in through the client, unfortunately after clicking login or registration the client crashes.

Later I tried to use the client from you, i.e. Intersect Client and Server.
So I downloaded versions 8.07 for Windows and Linux.
I took the server from Linux and put it on VPS with the resources removed.

I launched the game client on Windows.

In the server config file I changed the port to 5401 and in the client the host and port are the same.

Again, the server connects but after clicking login, the client immediately crashes.

Here I have the logs.

I did two more tests.

I started the server and client on Windows as localhost. He ran both the clean version and my old version.

I also deleted all files from the server and left only the server file to recreate everything, not only the resource folder.

Of course, I also test it on a clean client, replacing only the host with my IP/domain.
And unfortunately it's the same.
```
2023-10-14 12:23:32.226 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Menu.CreateCharacterWindow.UpdateDisplay() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\CreateCharacterWindow.cs:line 285
   at Intersect.Client.Interface.Menu.CreateCharacterWindow.classCombobox_ItemSelected(Base control, ItemSelectedEventArgs args) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\CreateCharacterWindow.cs:line 516
   at Intersect.Client.Framework.Gwen.Control.ComboBox.OnItemSelected(Base control, ItemSelectedEventArgs args) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\ComboBox.cs:line 284
   at Intersect.Client.Framework.Gwen.Control.ComboBox.AddItem(String label, String name, Object userData) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\ComboBox.cs:line 207
   at Intersect.Client.Interface.Menu.CreateCharacterWindow.Init() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\CreateCharacterWindow.cs:line 193
   at Intersect.Client.Interface.Menu.MainMenu.CreateCharacterCreation() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\MainMenu.cs:line 298
   at Intersect.Client.Interface.Menu.MainMenu.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\MainMenu.cs:line 209
   at Intersect.Client.Interface.Interface.DrawGui() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Interface.cs:line 219
   at Intersect.Client.Core.Graphics.Render(TimeSpan deltaTime, TimeSpan totalTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\Graphics.cs:line 593
   at Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 317
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 547
   at Intersect.Client.Core.ClientContext.InternalStart() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\ClientContext.cs:line 44
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) in D:\a\Intersect-Engine\Intersect-Engine\Intersect (Core)\Core\ApplicationContext`2.cs:line 224
```

### Steps to Reproduce

1.  Download Intersect winx64 full and Intersect linux x64 files
2. Upload the server file from the linux 64x folder to your vps server.
3. Run the server file on your Linux vps, once it has created the files, turn it off and change the port to 5401.
4. In the game client config, replace localhost with the server IP and the appropriate port.
5. launch the game client and click on login or registration.
You will enter the registration normally, but after entering the data and clicking register, it takes you to the desktop

:(

### Version with bug

0.8.07

### Last version that worked well

0.7.65

### Affected platforms

Windows, Linux

### Did you find any workaround?

I've tried several different ways but I can't get into the game in any of them.

### Relevant log output

```shell
2023-10-14 12:01:09.248 [Error] [NM] DataReceived: bad!

--------------------------------------------------------------------------------
2023-10-14 12:01:09.255 [Error] Error! Unexpected packet type: Empty

--------------------------------------------------------------------------------
2023-10-14 12:01:09.275 [Error] [NM] DataReceived: bad!

--------------------------------------------------------------------------------
2023-10-14 12:01:09.275 [Error] Error! Unexpected packet type: Empty

--------------------------------------------------------------------------------
2023-10-14 12:01:09.333 [Error] [NM] DataReceived: bad!

--------------------------------------------------------------------------------
2023-10-14 12:01:09.360 [Error] [NM] DataReceived: bad!

--------------------------------------------------------------------------------
2023-10-14 12:01:09.363 [Error] Error! Unexpected packet type: Empty

--------------------------------------------------------------------------------
2023-10-14 12:01:09.593 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Menu.LoginWindow.Show() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\LoginWindow.cs:line 156
   at Intersect.Client.Interface.Menu.MainMenu.SwitchToWindow(IMainMenuWindow mainMenuWindow) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\MainMenu.cs:line 343
   at Intersect.Client.Interface.Menu.MainMenu.LoginButton_Clicked(Base sender, ClickedEventArgs arguments) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\MainMenu.cs:line 308
   at Intersect.Client.Framework.Gwen.Control.Base.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Base.cs:line 2146
   at Intersect.Client.Framework.Gwen.Control.Button.OnClicked(Int32 x, Int32 y) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Button.cs:line 379
   at Intersect.Client.Framework.Gwen.Control.Button.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Button.cs:line 348
   at Intersect.Client.Framework.Gwen.Control.Base.InputMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Base.cs:line 2155
   at Intersect.Client.Framework.Gwen.Input.InputHandler.OnMouseClicked(Base canvas, Int32 mouseButton, Boolean down) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Input\InputHandler.cs:line 375
   at Intersect.Client.MonoGame.Input.MonoInput.CheckMouseButton(Keys modifier, ButtonState bs, MouseButtons mb) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\Input\MonoInput.cs:line 169
   at Intersect.Client.MonoGame.Input.MonoInput.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\Input\MonoInput.cs:line 272
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\Main.cs:line 111
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 265
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 547
   at Intersect.Client.Core.ClientContext.InternalStart() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\ClientContext.cs:line 44
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) in D:\a\Intersect-Engine\Intersect-Engine\Intersect (Core)\Core\ApplicationContext`2.cs:line 224


--------------------------------------------------------------------------------
2023-10-14 12:01:44.939 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Menu.LoginWindow.Show() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\LoginWindow.cs:line 156
   at Intersect.Client.Interface.Menu.MainMenu.SwitchToWindow(IMainMenuWindow mainMenuWindow) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\MainMenu.cs:line 343
   at Intersect.Client.Interface.Menu.MainMenu.LoginButton_Clicked(Base sender, ClickedEventArgs arguments) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Menu\MainMenu.cs:line 308
   at Intersect.Client.Framework.Gwen.Control.Base.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Base.cs:line 2146
   at Intersect.Client.Framework.Gwen.Control.Button.OnClicked(Int32 x, Int32 y) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Button.cs:line 379
   at Intersect.Client.Framework.Gwen.Control.Button.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Button.cs:line 348
   at Intersect.Client.Framework.Gwen.Control.Base.InputMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Base.cs:line 2155
   at Intersect.Client.Framework.Gwen.Input.InputHandler.OnMouseClicked(Base canvas, Int32 mouseButton, Boolean down) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Input\InputHandler.cs:line 375
   at Intersect.Client.MonoGame.Input.MonoInput.CheckMouseButton(Keys modifier, ButtonState bs, MouseButtons mb) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\Input\MonoInput.cs:line 169
   at Intersect.Client.MonoGame.Input.MonoInput.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\Input\MonoInput.cs:line 272
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\Main.cs:line 111
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 265
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 547
   at Intersect.Client.Core.ClientContext.InternalStart() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\ClientContext.cs:line 44
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) in D:\a\Intersect-Engine\Intersect-Engine\Intersect (Core)\Core\ApplicationContext`2.cs:line 224
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
I am not able to reproduce this, both Windows client and editor connect flawlessly to my Linux VPS-hosted server.

The VPS:
`lsb_release -a`
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

`dotnet --version`
```
7.0.112
```
(Ironically my VPS' dotnet is out of date)

Downloaded `intersect-linux-x64-patch-0.8.0-beta.7+build.9ebe17f65eb93fc8849c95e169bf9ead8042142c.zip`

Windows machine running the client/editor:
```
Version	10.0.19043 Build 19043
System Type	x64-based PC
```

`dotnet --version`
```
7.0.400
```

**Comment by cydyn** [comment]
My VPS:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

dotnet 7.0.402

in windows: 
Windows 10 x64
dotnet 7.0.401

From what I see, everything matches what you have
