### ISSUE TITLE
bug: quest/variable jackpot when switching characters instead of logging out

### ISSUE THREAD

**Issue by oomstdev** [AscensionGameDev/Intersect-Engine#2053]
### Description

There is a server crash that seems to be related to quest taking on accounts with multiple characters, doesn't seem to successfully write to the playerdb

TL:DR If I take a quest on 1 character then switch to another and take a quest it crashes when selecting a different character. There is more to it, but that's the summary.
This is an AWS, Ubuntu 22.04.3 LTS fresh install of .0.8.0.61 with Mariadb 10.6.12
Has also been confirmed on Windows local
Max characters 3
Starting with an account with 2 characters 
Basic quest

![2](https://github.com/AscensionGameDev/Intersect-Engine/assets/68409658/9b85caee-801e-413d-8ef8-8bb6dad4a238)

Basic event

![1](https://github.com/AscensionGameDev/Intersect-Engine/assets/68409658/340e1855-9a8b-498a-8e28-16a9e9379b09)

### Steps to Reproduce

Character 1 takes quest walk around a bit

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

Select character 2 walk around a bit

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

Select Character 1 and there's no issue. I can swap characters freely

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

Select character 2
Character 2 takes quest walk around a bit

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

Server crashes with log below
Restarting server and logging back in. 
Character 1 still has the quest in the log
Character 2 does NOT have the quest in their log
At this point I can swap without issue
Character 2 takes the quest walk around a bit

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

No crash
Quest is in both characters quest log
Freely switch around no issue
Create Character 3
Character 3 takes quest walk around a bit

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

Server crashes with log below
Delete Character 3 
Create Character 4
Take quest

> Open menu by either hitting escape key or clicking "Open Menu"button in lower right
> Click on "Characters"

Server crash with log below
I also create character 5 and test the whole thing but swap maps before going to character select and it crashed
I also confirmed that using Logout instead prevents the issue.

### Version with bug

.0.8.0.61

### Last version that worked well

Unknown

### Affected platforms

Windows, Linux

### Did you find any workaround?

Use the logout and not the character select

### Relevant log output

```shell
--------------------------------------------------------------------------------
2023-11-11 22:05:55.071 [Error] Jackpot! Concurrency Bug For User, Player, BankSlot, HotbarSlot, InventorySlot, Quest, SpellSlot 
2023-11-11 22:05:55.071 [Error] DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
    Stack:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\IntersectDbContext.cs:line 205


--------------------------------------------------------------------------------
2023-11-11 22:05:55.072 [Error] Entry Type [Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry / Modified]
--------------------
Type: Intersect.Server.Database.PlayerData.Players.Quest
	Id (Token: False): Proposed: 08dbe302-6036-49da-818a-5d441deca9bd  Original Value: 08dbe302-6036-49da-818a-5d441deca9bd  Database Value: null
	Completed (Token: False): Proposed: False  Original Value: False  Database Value: null
	PlayerId (Token: False): Proposed: adcaec3a-8210-4d80-b179-0f0b9f35cabb  Original Value: adcaec3a-8210-4d80-b179-0f0b9f35cabb  Database Value: null
	QuestId (Token: False): Proposed: a2a9acbc-3e5a-42de-b608-6639853db747  Original Value: a2a9acbc-3e5a-42de-b608-6639853db747  Database Value: null
	TaskId (Token: False): Proposed: 2ca248dd-8bad-4f45-8302-0dd6870d17a1  Original Value: 2ca248dd-8bad-4f45-8302-0dd6870d17a1  Database Value: null
	TaskProgress (Token: False): Proposed: 0  Original Value: 0  Database Value: null




--------------------------------------------------------------------------------
2023-11-11 22:05:55.073 [Error] Received unhandled exception from System.Threading.Thread: Failed to save Intersect.Server.Database.PlayerData.MySqlPlayerContext, shutting down to prevent rollbacks!

--------------------------------------------------------------------------------
2023-11-11 22:05:55.073 [Error] Exception: Failed to save Intersect.Server.Database.PlayerData.MySqlPlayerContext, shutting down to prevent rollbacks!


--------------------------------------------------------------------------------
2023-11-11 22:05:55.074 [Info] Saving updated server variable values

--------------------------------------------------------------------------------
2023-11-11 22:05:55.074 [Info] Saving online users/players... (120ms)

--------------------------------------------------------------------------------
2023-11-11 22:05:55.075 [Info] Saving loaded guilds....

--------------------------------------------------------------------------------
2023-11-11 22:05:55.075 [Info] Online users/players saved. (120ms)

--------------------------------------------------------------------------------
2023-11-11 22:05:55.077 [Info] Shutting down the console thread... (122ms)

--------------------------------------------------------------------------------
2023-11-11 22:05:55.302 [Info] Connection approved [8f7f0e00-a2e2-476c-bd97-8864975f0a2a].

--------------------------------------------------------------------------------
2023-11-11 22:05:55.302 [Info] Connected [8f7f0e00-a2e2-476c-bd97-8864975f0a2a].

--------------------------------------------------------------------------------
2023-11-11 22:05:56.078 [Info] Base dispose. (1123ms)

--------------------------------------------------------------------------------
2023-11-11 22:05:56.078 [Info] Finished disposing server context. (1123ms)
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by cydyn** [comment]
I did this crash on a clean intersect.
I'll break it down in points:
1. We download versions 0.7.65 and 0.8.67 of Linux and Windows.
2. On version 0.7.65, we create the entire database, and in the editor on this server we create a small quest.
3. We upload the 0.8.67 Linux server to our Linux VPS server.
4. We upload the database from 0.7.65 to the Linux server, then start the Linux server and use the READY command to migrate the db.
5. Run the Windows client version 0.8.67.
6. Log in to the created account from 0.7.65 on our client 0.8.67 (because to do this small quest we needed an account to enter the editor)
7. Our old account with a character created on 0.7.65 will work properly, we will take the quest, click change character in the menu and there will be no crash.
However, all you need to do is delete the character and create a new one, or create a new one in general, take the quest, and click change character in the menu and the server will automatically kick it completely.

I hope this is understandable
