### ISSUE TITLE
bug: server crashes when logging out after changing the maximum spell slot

### ISSUE THREAD

**Issue by dhmello** [AscensionGameDev/Intersect-Engine#2122]
### Description

I increased the maximum number of spells that the player can have on my server, now when entering the character's screen the equipment does not load and also when the player logs out, the server crashes.

### Steps to Reproduce

1. Have an old database, where the maximum spells in the server settings are the default value.
2 - Change the maximum spells to 100 (in my case it was this value)
3 - Log in with the existing character, notice that he will appear without clothes (paperdoll), but when logged in he will render the clothes normally.
4 - disconnect the character and watch the bug crash the server.

### Version with bug

0.8.0.0

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/13499863/errors-Intersect.Server.log)

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment]
Update: If i back to 35 spells slots, the bug dont happen

**Comment by Thomasfds** [comment]
Encounter this issue too. 
[Intersect Server-2024_01_24-14_09_35_896.log](https://github.com/AscensionGameDev/Intersect-Engine/files/14039115/Intersect.Server-2024_01_24-14_09_35_896.log)
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/14039116/errors-Intersect.Server.log)

**Comment by cydyn** [comment]
I checked on versions 0.8.05, 0.8.88, 0.8.36.
This does not work properly on any of these versions and immediately results in exiting the server.
1. I changed the maxslotsbank server configuration from 500 (default) to 50.
2. On the server, I created an event to open the bank and the item I would like to place there.
3. After dragging an item onto the bank window, it automatically launches the game client.

Error logs client:

2024-01-25 08:40:49.480 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
    Stack:    at Intersect.Client.Interface.Game.Inventory.InventoryItem.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Game\Inventory\InventoryItem.cs:line 263
   at Intersect.Client.Interface.Game.Inventory.InventoryWindow.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Game\Inventory\InventoryWindow.cs:line 199
   at Intersect.Client.Interface.Game.Menu.Update(Boolean updateQuestLog) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Game\Menu.cs:line 157
   at Intersect.Client.Interface.Game.GameInterface.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Game\GameInterface.cs:line 322
   at Intersect.Client.Interface.Interface.DrawGui() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Interface\Interface.cs:line 219
   at Intersect.Client.Core.Graphics.Render(TimeSpan deltaTime, TimeSpan totalTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\Graphics.cs:line 593
   at Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 317
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 547
   at Intersect.Client.Core.ClientContext.InternalStart() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\ClientContext.cs:line 44
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) in D:\a\Intersect-Engine\Intersect-Engine\Intersect (Core)\Core\ApplicationContext`2.cs:line 224

**Comment by cydyn** [comment]
It's different with witchcraft. A value below the default works fine.
Values ​​above 35 (I checked 100 and 90) cause a concurrency error.

Logs Server: 

2024-01-25 08:49:04.341 [Error] Jackpot! Concurrency Bug For cydyn in Created Context 
2024-01-25 08:49:04.341 [Error] DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
    Stack:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server\Database\IntersectDbContext.cs:line 171
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server\Database\IntersectDbContext.cs:line 163
   at Intersect.Server.Database.PlayerData.User.Save(PlayerContext playerContext, Boolean force, Boolean create) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server\Database\PlayerData\User.cs:line 375


--------------------------------------------------------------------------------
2024-01-25 08:49:04.342 [Error] Entry Type [Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry / Modified]
--------------------
Type: Intersect.Server.Database.PlayerData.Players.SpellSlot
	Id (Token: False): Proposed: 0053fbfa-3d18-4c94-8c72-53cdcd9ac46e  Original Value: 0053fbfa-3d18-4c94-8c72-53cdcd9ac46e  Database Value: null
	PlayerId (Token: False): Proposed: dfb67a40-94d1-4c07-a963-8907aec2a8bc  Original Value: dfb67a40-94d1-4c07-a963-8907aec2a8bc  Database Value: null
	Slot (Token: False): Proposed: 37  Original Value: 37  Database Value: null
	SpellId (Token: False): Proposed: 00000000-0000-0000-0000-000000000000  Original Value: 00000000-0000-0000-0000-000000000000  Database Value: null




--------------------------------------------------------------------------------
2024-01-25 08:49:04.344 [Error] Received unhandled exception from System.Threading.Thread: Failed to save user, shutting down to prevent rollbacks!

--------------------------------------------------------------------------------
2024-01-25 08:49:04.344 [Error] Exception: Failed to save user, shutting down to prevent rollbacks!

**Comment by cydyn** [comment]
Oh! The problem with the bank is also on version 0.7.65
You can deposit items, but only from the inventory by right-clicking on the item and deposit.
When moving an item with the mouse to the bank, the client immediately crashes
Spells no problem

**Comment by cydyn** [comment]
Additionally, I didn't really think about it, but since there are 500 places in the bank by default, there must be an error somewhere because it only detects 100.

**Comment by cydyn** [comment]
@Thomasfds However, there is no problem for me. You need to change Initialbankslots in the config, not MaxSlots.
These are two different things

**Comment by cydyn** [comment]
@theceltos At the moment, this error can be solved in one way:
1. Start the server.
2. How to create playerdata.db files, change maxspells in the config to higher than 35
3. Turn off the server.
4. Delete playerdata.db
5. Start the server to recreate playerdata.db, thanks to which the database will load more slots for the player and the concurrency error will not appear

**Comment by theceltos** [comment]
OK regarding the method to avoid bugs, but the bug will not cease to exist, what will we do with a project where there are several accounts, characters, items in the player database?
Ahh it bugged, am I going to delete it and do it again?

I believe this is a BUG, and should not be resolved as a workaround.

If it is not resolved, some other project will face the same problem down the road. We're just hiding the elephant in a room where no one can see...

**Comment by cydyn** [comment]
Yes, this is just a workaround, but I think that the number of available spells is actually set at the beginning, before we start the server, even for visual reasons. We make a menu and we probably don't increase it

This is a bug that needs to be fixed, but you can set the value to 100 spells and only use 50
