### ISSUE TITLE
bug: client crashes when hovering over an item in the hotkey

### ISSUE THREAD

**Issue by theceltos** [AscensionGameDev/Intersect-Engine#2135]
### Description

client crashes when hovering over an item in the hotkey, when the item is not in your backpack either.

### Steps to Reproduce

Have the item in your inventory.
Drag to the hotbar.
Store the item in the bank.
Hover over the item in the hotbar.
see the bug

### Version with bug

0.8.0.0

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Relevant log output

```shell
2023-12-03 23:29:14.557 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Game.DescriptionWindows.ItemDescriptionWindow.SetupEquipmentInfo() in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\Interface\Game\DescriptionWindows\ItemDescriptionWindow.cs:line 209
   at Intersect.Client.Interface.Game.DescriptionWindows.ItemDescriptionWindow.SetupDescriptionWindow() in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\Interface\Game\DescriptionWindows\ItemDescriptionWindow.cs:line 99
   at Intersect.Client.Interface.Game.DescriptionWindows.ItemDescriptionWindow..ctor(ItemBase item, Int32 amount, Int32 x, Int32 y, ItemProperties itemProperties, String titleOverride, String valueLabel, Boolean centerOnPosition) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\Interface\Game\DescriptionWindows\ItemDescriptionWindow.cs:line 54
   at Intersect.Client.Interface.Game.Hotbar.HotbarItem.pnl_HoverEnter(Base sender, EventArgs arguments) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\Interface\Game\Hotbar\HotbarItem.cs:line 183
   at Intersect.Client.Framework.Gwen.Control.Base.OnMouseEntered() in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Base.cs:line 2240
   at Intersect.Client.Framework.Gwen.Input.InputHandler.UpdateHoveredControl(Base inCanvas) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Input\InputHandler.cs:line 542
   at Intersect.Client.Framework.Gwen.Control.Canvas.Input_MouseMoved(Int32 x, Int32 y, Int32 dx, Int32 dy) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Canvas.cs:line 310
   at Intersect.Client.Framework.Gwen.Input.IntersectInput.ProcessMessage(Object message) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client.Framework\Gwen\Input\IntersectInput.cs:line 96
   at Intersect.Client.MonoGame.Input.MonoInput.Update(TimeSpan elapsed) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\MonoGame\Input\MonoInput.cs:line 405
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\Core\Main.cs:line 111
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 284
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 566
   at Intersect.Client.Core.ClientContext.InternalStart() in E:\The Celtos Game\Engine\Intersect-Engine\Intersect.Client\Core\ClientContext.cs:line 41
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) in E:\The Celtos Game\Engine\Intersect-Engine\Intersect (Core)\Core\ApplicationContext`2.cs:line 239


--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment]
This bug is happening with tools, such as axe, pickaxe, etc...
It appears to have appeared after the Stats Range update

**Comment by theceltos** [comment]
I don't know how but the bug is no longer happening.

**Comment by theceltos** [comment]
The bug is happening again, now I discovered that it happens in the crafting menu, when hovering the mouse over the sword the game closes, gives the same log

**Comment by TimtyG** [comment]
@theceltos I'll look into this tonight, let's give Panda some rest
