### ISSUE TITLE
bug: Editor crashes when trying to download map previews

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#2167]
### Description

Trying to download all previews or missing previews in the map editor caused the editor to crash.

### Steps to Reproduce

1. login to intersect map editor
2. click the option to try and download missing or all previews
3. watch the editor crash

### Version with bug

0.8.0.132

### Last version that worked well

b7

### Affected platforms

Windows

### Did you find any workaround?

no.

### Relevant log output

```shell
Server cmd promt errors:

container@pterodactyl~ Server marked as running...
2024-02-17 14:10:34.320 [Error] MessagePackSerializationException: Failed to deserialize Intersect.Network.PackedIntersectPacket value.
    Stack:    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at Intersect.Network.MessagePacker.Deserialize(Byte[] packetData, Boolean silent) in /home/runner/work/Intersect-Engine/Intersect-Engine/Intersect (Core)/Network/MessagePacker.cs:line 53
Caused By
MessagePackSerializationException: Unexpected msgpack code 10 (positive fixint) encountered.
    Stack:    at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.ReadArrayHeader()
   at MessagePack.Formatters.Intersect_Network_PackedIntersectPacketFormatter1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
2024-02-17 14:15:42.923 [Error] MessagePackSerializationException: Failed to deserialize Intersect.Network.PackedIntersectPacket value.
    Stack:    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at Intersect.Network.MessagePacker.Deserialize(Byte[] packetData, Boolean silent) in /home/runner/work/Intersect-Engine/Intersect-Engine/Intersect (Core)/Network/MessagePacker.cs:line 53
Caused By
MessagePackSerializationException: Unexpected msgpack code 99 (positive fixint) encountered.
    Stack:    at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.ReadArrayHeader()
   at MessagePack.Formatters.Intersect_Network_PackedIntersectPacketFormatter1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by NikoCummings** [comment]
With this being said, if your in the map gride view and double left click a map square (which are currently all green and cannot be loaded). It does not take you to the map you clicked on and switch over to map editor view. It stays in the map grid view (without refreshing the green square and loading the map image as it previously did)  and you have to manually click the map editor tab to view and edit the map you double left clicked on.
