### ISSUE TITLE
bug: Editing Variables in Editor causes editor to crash (When Multipling Variables by a number)

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#2244]
### Description

When attempting to edit a Common Event, the Editor will crash when editing a Player Variable that is being Multiplied by a Number.

Player Variable is set to Integer and being Multiplied by 10

When I try to edit a common event line that is a **Player Variable Multiply by a Number** - that's what causes the crash.

This is what i've tested:
Set Player Variable to a number = No Crash
Set Player Variable to a random number = No Crash
Set Player Variable to another Variable = No Crash
Set Player Variable to Multiple by another Variable = No Crash
Ser Player Variable to Multiple by a number = Crash

Happens with all Player Variables that I try to just multiple.
I can change that Player Variable in other ways without a crash (I can multiply the variable by another variable just fine)

![Common Event Crash multiply](https://github.com/AscensionGameDev/Intersect-Engine/assets/110916959/6adfbb6c-e0a5-49dc-8f9e-cf89e1e05b3e)

### Steps to Reproduce

1. Create Player Variable as Integer
2. Create Common Event with a line that; Set Player Variable to Multiple by 10
3. Save Common Event, then reopen and attempt to right-click 'Edit'

### Version with bug

8.0.147

### Last version that worked well

B7 seemed to work fine

### Affected platforms

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
--------------------------------------------------------------------------------
2024-05-05 15:51:05.260 [Error] ArgumentException: Failed to get RelatedVariableType attribute for VariableType enum, value was Multiply (Parameter 'value')
    Stack:    at Intersect.Extensions.VariableModExtensions.GetRelatedVariableType(VariableMod value) in D:\a\Intersect-Engine\Intersect-Engine\Intersect (Core)\Extensions\VariableModExtensions.cs:line 30
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable.TryLoadNumericMod(VariableMod variableMod) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 278
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable.UpdateFormElements() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 143
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable.InitEditor() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 106
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable..ctor(SetVariableCommand refCommand, FrmEvent editor) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 45
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.OpenEditCommand(EventCommand command) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1204
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.btnEdit_Click(Object sender, EventArgs e) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1593
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


--------------------------------------------------------------------------------

From the Server Console (when having an admin character logged in) I got this:

> 2024-05-04 22:16:25.417 [Error] Jackpot! Concurrency Bug For User, Player, BankSlot, HotbarSlot, InventorySlot, Quest, SpellSlot, PlayerVariable, UserVariable
2024-05-04 22:16:25.417 [Error] See logs for more information.
2024-05-04 22:16:25.418 [Error] This failure was wholly caused by user 8b4fd97b-01a6-4bbc-b077-590c3968d31b
[Modified] Intersect.Server.Database.PlayerData.Players.PlayerVariable (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry)
User Id 8b4fd97b-01a6-4bbc-b077-590c3968d31b
        Id (Token: False): Proposed: 0209b42c-7be7-4f10-8ed3-357cd7839bb3 Original Value: 0209b42c-7be7-4f10-8ed3-357cd7839bb3 Database Value: null
        Json (Token: False): Proposed: {"Type":2,"Value":0} Original Value: {"Type":2,"Value":0} Database Value: null
        PlayerId (Token: False): Proposed: b47e98cf-eab3-4cb2-92a0-725f497087d5 Original Value: b47e98cf-eab3-4cb2-92a0-725f497087d5 Database Value: null
        VariableId (Token: False): Proposed: 16b45022-1bf8-4067-b8b3-a7ad1ef1ff0a Original Value: 16b45022-1bf8-4067-b8b3-a7ad1ef1ff0a Database Value: null

   at System.Environment.get_StackTrace()
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\IntersectDbContext.cs:line 223
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\IntersectDbContext.cs:line 193
   at Intersect.Server.Database.PlayerData.User.Save(PlayerContext playerContext, Boolean force, Boolean create) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\PlayerData\User.cs:line 413
   at Intersect.Server.Database.PlayerData.User.Save(Boolean force, Boolean create) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\PlayerData\User.cs:line 310
   at Intersect.Server.Database.PlayerData.User.Save(Boolean force) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\PlayerData\User.cs:line 308
   at Amib.Threading.Internal.WorkItemsGroupBase.<>c__DisplayClass46_0`2.<QueueWorkItem>b__0(Object state)
   at Amib.Threading.Internal.WorkItem.ExecuteWorkItem()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.ExecuteWorkItem(WorkItem workItem)
   at Amib.Threading.SmartThreadPool.ProcessQueuedItems()

2024-05-04 22:16:25.420 [Error] DbUpdateConcurrencyException occurred, please review the logs for more information.
2024-05-04 22:18:25.427 [Error] Jackpot! Concurrency Bug For User, Player, BankSlot, HotbarSlot, InventorySlot, Quest, SpellSlot, PlayerVariable, UserVariable
2024-05-04 22:18:25.427 [Error] See logs for more information.
2024-05-04 22:18:25.427 [Error] This failure was wholly caused by user 8b4fd97b-01a6-4bbc-b077-590c3968d31b
[Modified] Intersect.Server.Database.PlayerData.Players.PlayerVariable (Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry)
User Id 8b4fd97b-01a6-4bbc-b077-590c3968d31b
        Id (Token: False): Proposed: 0209b42c-7be7-4f10-8ed3-357cd7839bb3 Original Value: 0209b42c-7be7-4f10-8ed3-357cd7839bb3 Database Value: null
        Json (Token: False): Proposed: {"Type":2,"Value":0} Original Value: {"Type":2,"Value":0} Database Value: null
        PlayerId (Token: False): Proposed: b47e98cf-eab3-4cb2-92a0-725f497087d5 Original Value: b47e98cf-eab3-4cb2-92a0-725f497087d5 Database Value: null
        VariableId (Token: False): Proposed: 16b45022-1bf8-4067-b8b3-a7ad1ef1ff0a Original Value: 16b45022-1bf8-4067-b8b3-a7ad1ef1ff0a Database Value: null

   at System.Environment.get_StackTrace()
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges(Boolean acceptAllChangesOnSuccess) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\IntersectDbContext.cs:line 223
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Intersect.Server.Database.IntersectDbContext`1.SaveChanges() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\IntersectDbContext.cs:line 193
   at Intersect.Server.Database.PlayerData.User.Save(PlayerContext playerContext, Boolean force, Boolean create) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\PlayerData\User.cs:line 413
   at Intersect.Server.Database.PlayerData.User.Save(Boolean force, Boolean create) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\PlayerData\User.cs:line 310
   at Intersect.Server.Database.PlayerData.User.Save(Boolean force) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Database\PlayerData\User.cs:line 308
   at Amib.Threading.Internal.WorkItemsGroupBase.<>c__DisplayClass46_0`2.<QueueWorkItem>b__0(Object state)
   at Amib.Threading.Internal.WorkItem.ExecuteWorkItem()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.ExecuteWorkItem(WorkItem workItem)
   at Amib.Threading.SmartThreadPool.ProcessQueuedItems()

2024-05-04 22:18:25.429 [Error] DbUpdateConcurrencyException occurred, please review the logs for more information.
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
thanks, managed to reproduce the issue:

```csharp

--------------------------------------------------------------------------------
2024-05-05 21:56:43.451 [Error] ArgumentException: Failed to get RelatedVariableType attribute for VariableType enum, value was Multiply (Parameter 'value')
    Stack:    at Intersect.Extensions.VariableModExtensions.GetRelatedVariableType(VariableMod value) in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect (Core)\Extensions\VariableModExtensions.cs:line 30
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable.TryLoadNumericMod(VariableMod variableMod) in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 278
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable.UpdateFormElements() in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 143
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable.InitEditor() in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 106
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandVariable..ctor(SetVariableCommand refCommand, FrmEvent editor) in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Variable.cs:line 45
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.OpenEditCommand(EventCommand command) in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1204
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.btnEdit_Click(Object sender, EventArgs e) in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1593
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


--------------------------------------------------------------------------------
```
