### ISSUE TITLE
bug: server crash when crafting

### ISSUE THREAD

**Issue by Northgatenoob** [AscensionGameDev/Intersect-Engine#2245]
### Description

When crafting a specific craft my server crashes. It doesn't crash when crafting another craft using the same number of items.

### Steps to Reproduce

1. Bring craft to crafting table.
2. Select craft to craft.
3. immediate crash after hitting craft.

The item is nothing special, virtually the same as the other crafts with a higher sell value. It does not run any events or do anything except exist in the inventory.

https://github.com/AscensionGameDev/Intersect-Engine/assets/86127446/70782c51-30e6-413d-a876-404a994c2ed6

### Version with bug

v0.8.0.152

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

No.

### Relevant log output

```shell
2024-05-07 22:01:46.563 [Info] Discovered service type: Intersect.Plugins.PluginService

--------------------------------------------------------------------------------
2024-05-07 22:01:46.564 [Info] Discovered service type: Intersect.Server.Core.LogicService

--------------------------------------------------------------------------------
2024-05-07 22:01:46.565 [Info] Discovered service type: Intersect.Server.Web.ApiService

--------------------------------------------------------------------------------
2024-05-07 22:01:46.565 [Info] Discovered service type: Intersect.Server.Core.ConsoleService

--------------------------------------------------------------------------------
2024-05-07 22:01:46.579 [Warn] Directory was specified as a plugin directory but does not exist: 'resources\plugins'

--------------------------------------------------------------------------------
2024-05-07 22:01:46.579 [Info] Discovered 0 plugins:


--------------------------------------------------------------------------------
InvalidPortCheckerResponse

--------------------------------------------------------------------------------
Port 5400 is not open, trying UPnP...

--------------------------------------------------------------------------------
UPnP Service Initialization Succeeded

--------------------------------------------------------------------------------
Successfully auto port forwarded udp port 5400 using UPnP.

--------------------------------------------------------------------------------
InvalidPortCheckerResponse

--------------------------------------------------------------------------------
UPnP supposedly succeeded but the server is not accessible on port 5400, check the firewall of the machine this server is running on.

--------------------------------------------------------------------------------
2024-05-07 22:01:50.182 [Info] Unpacking appsettings...

--------------------------------------------------------------------------------
2024-05-07 22:01:57.459 [Info] Connection approved [757c54cc-9375-4a79-b2b2-490b7469cb53].

--------------------------------------------------------------------------------
2024-05-07 22:01:57.459 [Info] Connected [757c54cc-9375-4a79-b2b2-490b7469cb53].

--------------------------------------------------------------------------------
2024-05-07 22:02:09.150 [Error] Received unhandled exception from System.Threading.Thread: Object reference not set to an instance of an object.

--------------------------------------------------------------------------------
2024-05-07 22:02:09.150 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Server.Entities.Player.ShouldCancelCrafting() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Entities\Player.cs:line 4185
   at Intersect.Server.Entities.Player.Update(Int64 timeMs) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Entities\Player.cs:line 900
   at Intersect.Server.Maps.MapInstance.UpdateEntities(Int64 timeMs) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Maps\MapInstance.cs:line 1293
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Maps\MapInstance.cs:line 281
   at Intersect.Server.Core.LogicService.LogicThread.UpdateMap(MapInstance mapInstance, Boolean onlyProjectiles) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Server.Core\Core\LogicService.LogicThread.cs:line 403


--------------------------------------------------------------------------------
2024-05-07 22:02:09.159 [Info] Acquiring context lock... (0ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:09.159 [Info] Acquired. (0ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:09.160 [Info] Beginning context dispose. (0ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:09.160 [Info] Disposing network... (0ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:09.163 [Info] Disconnected [757c54cc-9375-4a79-b2b2-490b7469cb53].

--------------------------------------------------------------------------------
2024-05-07 22:02:09.203 [Info] Saving updated server variable values

--------------------------------------------------------------------------------
2024-05-07 22:02:09.203 [Info] Saving online users/players... (43ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:09.203 [Info] Saving loaded guilds....

--------------------------------------------------------------------------------
2024-05-07 22:02:09.203 [Info] Online users/players saved. (43ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:09.204 [Info] Shutting down the console thread... (43ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:10.215 [Info] Base dispose. (1054ms)

--------------------------------------------------------------------------------
2024-05-07 22:02:10.215 [Info] Finished disposing server context. (1055ms)

--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
@Northgatenoob are you able to compile your own solutions? if so, could you give this branch a try and see if the issue persists?

https://github.com/AscensionGameDev/Intersect-Engine/pull/2246

**Comment by Northgatenoob** [comment]
I have not been able to yet.
