### ISSUE TITLE
bug:  Client crash when launching projectile and transitioning between maps.

### ISSUE THREAD

**Issue by AlefMichel** [AscensionGameDev/Intersect-Engine#2276]
### Description

when you launch a project continuously and move from one stage to another, the client closes

### Steps to Reproduce

1. Create a Weapon and add a projectile.
2. Attack a monster and walk between maps.

### Version with bug

0.8.0.164

### Last version that worked well

none

### Affected platforms

Windows

### Relevant log output

```shell
2024-06-10 22:19:14.258 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at Intersect.Client.Entities.Projectiles.Projectile.GetProjectileX(ProjectileSpawns spawn) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Entities\Projectiles\Projectile.cs:line 370
   at Intersect.Client.Entities.Projectiles.Projectile.GetProjectileLerping(ProjectileSpawns spawn, Boolean isXAxis) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Entities\Projectiles\Projectile.cs:line 468
   at Intersect.Client.Entities.Projectiles.Projectile.Update() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Entities\Projectiles\Projectile.cs:line 365
   at Intersect.Client.Core.Main.ProcessGame() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\Main.cs:line 313
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\Main.cs:line 111
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 284
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\MonoGame\IntersectGame.cs:line 566
   at Intersect.Client.Core.ClientContext.InternalStart() in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Client\Core\ClientContext.cs:line 41
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) in D:\a\Intersect-Engine\Intersect-Engine\Intersect (Core)\Core\ApplicationContext`2.cs:line 239
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
can you record video please?

**Comment by AlefMichel** [comment]
https://github.com/AscensionGameDev/Intersect-Engine/assets/128094550/59dd5312-aff1-4d58-a7ef-1feef3f562f6

sure here it is.

**Comment by WeylonSantana** [comment]
@AlefMichel when you are in other map you can shoot?

**Comment by theceltos** [comment]
Same here, @WeylonSantana I told you privately about this bug, I thought it was just me

**Comment by WeylonSantana** [comment]
> Same here, @WeylonSantana I told you privately about this bug, I thought it was just me

I don't know if you saw it, but there's already a link answering this

**Comment by italocra** [comment]
> > Same here, @WeylonSantana I told you privately about this bug, I thought it was just me
> 
> I don't know if you saw it, but there's already a pr fixing this

How do I use this to fix the bug?
