### ISSUE TITLE
bug: Server Game Time Exception

### ISSUE THREAD

**Issue by Irokaiser** [AscensionGameDev/Intersect-Engine#2394]
### Description

After running the server for ~24 hours this exception is thrown and the server shuts down.

Latest Intersect Build with no custom edits.

```
2024-11-16 01:46:14.645 [Error] Received unhandled exception from System.Threading.Thread: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')

Server is now closing. Please wait while your game and player data is saved!

2024-11-16 01:46:14.663 [Error] ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')
    Stack:    at System.DateTime.ThrowDateArithmetic(Int32 param)
   at System.DateTime.AddTicks(Int64 value)
   at Intersect.Server.General.Time.Update() in /home/runner/work/TessaPrimeSource/TessaPrimeSource/Intersect.Server.Core/General/Time.cs:line 48
   at Intersect.Server.Core.LogicService.LogicThread.ThreadStart(ServerContext serverContext) in /home/runner/work/TessaPrimeSource/TessaPrimeSource/Intersect.Server.Core/Core/LogicService.LogicThread.cs:line 336

```

### Steps to Reproduce

- Run Latest Intersect Server Build (Bug encountered when running on Linux Ubuntu 22.04 environment)
- Wait ~24 hours

### Version with bug

0.8.0-beta.239

### Last version that worked well

0.7.0 I think

### Affected platforms

Linux, I was *not* able test on other platforms

### Relevant log output

```shell
2024-11-16 01:46:14.645 [Error] Received unhandled exception from System.Threading.Thread: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')

Server is now closing. Please wait while your game and player data is saved!

2024-11-16 01:46:14.663 [Error] ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 'value')
    Stack:    at System.DateTime.ThrowDateArithmetic(Int32 param)
   at System.DateTime.AddTicks(Int64 value)
   at Intersect.Server.General.Time.Update() in /home/runner/work/TessaPrimeSource/TessaPrimeSource/Intersect.Server.Core/General/Time.cs:line 48
   at Intersect.Server.Core.LogicService.LogicThread.ThreadStart(ServerContext serverContext) in /home/runner/work/TessaPrimeSource/TessaPrimeSource/Intersect.Server.Core/Core/LogicService.LogicThread.cs:line 336

```
```


### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Irokaiser** [comment]
Encountered again, seemingly every 24 Hours.

**Comment by Arufonsu** [comment]
Try this: within the time update method, add a try-catch block around where the time's Add method is called at in order to catch any ArgumentOutOfRangeException and reset the sGameTime to DateTime.Now if an exception occurs (this _should_ prevent the server from crashing due to un-representable DateTime values).

https://diffy.org/diff/534a44ab91df4

[time_fix_attempt.patch](https://github.com/user-attachments/files/17794122/time_fix_attempt.patch)

Thanks for reporting, let us know if that ^ helps  !

**Comment by lodicolo** [comment]
Since we haven't gotten any additional information for this issue so that we can reproduce it and fix it correctly, I've added debugging information in e799f73 and I'm closing this until we get thorough information on the cause.
