### ISSUE TITLE
bug: Can't launch editor

### ISSUE THREAD

**Issue by WereAlpaca** [AscensionGameDev/Intersect-Engine#2396]
### Description

The launcher shows an error and points me to the error log, before this happened I was quite fast with saving and exiting a map, possibly exiting too quickly. 

### Steps to Reproduce

I was not able to reproduce the bug.

### Version with bug

0.8.0.3

### Last version that worked well

0.8.0.3

### Affected platforms

Windows

### Did you find any workaround?

PC Reset seems to have fixed the issue

### Relevant log output

```shell
--------------------------------------------------------------------------------
2024-11-17 22:57:37.167 [Error] IOException: The process cannot access the file 'C:\Users\nicka\Documents\GitHub\TessaPrime\Tessa Prime Main\Client and Editor\sqlite3.dll' because it is being used by another process.
    Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Intersect.Editor.Core.Program.Main() in D:\a\TessaPrimeSource\TessaPrimeSource\Intersect.Editor\Core\Program.cs:line 52


--------------------------------------------------------------------------------
2024-11-17 22:57:39.539 [Error] IOException: The process cannot access the file 'C:\Users\nicka\Documents\GitHub\TessaPrime\Tessa Prime Main\Client and Editor\sqlite3.dll' because it is being used by another process.
    Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Intersect.Editor.Core.Program.Main() in D:\a\TessaPrimeSource\TessaPrimeSource\Intersect.Editor\Core\Program.cs:line 52


--------------------------------------------------------------------------------
2024-11-17 22:57:42.072 [Error] IOException: The process cannot access the file 'C:\Users\nicka\Documents\GitHub\TessaPrime\Tessa Prime Main\Client and Editor\sqlite3.dll' because it is being used by another process.
    Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Intersect.Editor.Core.Program.Main() in D:\a\TessaPrimeSource\TessaPrimeSource\Intersect.Editor\Core\Program.cs:line 52


--------------------------------------------------------------------------------
2024-11-17 22:57:56.068 [Error] IOException: The process cannot access the file 'C:\Users\nicka\Documents\GitHub\TessaPrime\Tessa Prime Main\Client and Editor\sqlite3.dll' because it is being used by another process.
    Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Intersect.Editor.Core.Program.Main() in D:\a\TessaPrimeSource\TessaPrimeSource\Intersect.Editor\Core\Program.cs:line 52


--------------------------------------------------------------------------------
2024-11-17 22:58:38.304 [Error] IOException: The process cannot access the file 'C:\Users\nicka\Documents\GitHub\TessaPrime\Tessa Prime Main\Client and Editor\sqlite3.dll' because it is being used by another process.
    Stack:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Intersect.Editor.Core.Program.Main() in D:\a\TessaPrimeSource\TessaPrimeSource\Intersect.Editor\Core\Program.cs:line 52


--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WereAlpaca** [comment]
Sorry for the newbie bug report! First time doing this.

**Comment by WeylonSantana** [comment]
`The process cannot access the file 'C:\Users\nicka\Documents\GitHub\TessaPrime\Tessa Prime Main\Client and Editor\sqlite3.dll' because it is being used by another process`

This error only happens in one situation, when the editor is already open, or at least its process.
Maybe you were editing the game, it must have crashed, and it closed or didn't open correctly, I don't know. But its process remained open in the task manager.

When you try to open another one, it will cause this error.

It's not a bug, but it shouldn't just crash, as devs should put a warning.

To solve your case, if it happens again, open the task manager and in "details" look for the remaining editor process still open and end it.

**Comment by Arufonsu** [comment]
This is not a bug but still is likely to be an issue at times, but as @WeylonSantana mentioned there's a workaround using the taskmanager, thanks for reporting anyways !
