### ISSUE TITLE
Copy and paste between events  crash  the editor

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#257]
**Describe the bug**
Copy and paste between events  crash  the editor

**Version Encountered**
0.6.2.421

**To Reproduce**
[Bug.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/4809404/Bug.zip)

**Expected behavior**
Copy and paste between events

**Logs**
[errors-Intersect_Editor.log](https://github.com/AscensionGameDev/Intersect-Engine/files/4809406/errors-Intersect_Editor.log)
```2020-06-21 12:04:53.518 [Error] 
  Message: The given key was not present in the dictionary.
    Stack:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Intersect.Editor.Forms.Editors.Events.CommandPrinter.PrintCommandList(EventPage page, List`1 commandList, String indent, ListBox lstEventCommands, List`1 mCommandProperties, MapInstance map) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\CommandPrinter.cs:line 185
   at Intersect.Editor.Forms.Editors.Events.CommandPrinter.PrintCommandList(EventPage page, List`1 commandList, String indent, ListBox lstEventCommands, List`1 mCommandProperties, MapInstance map) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\CommandPrinter.cs:line 131
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.ListPageCommands() in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1077
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.btnPaste_Click(Object sender, EventArgs e) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1618
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Operating System:**
Windows

**Comment by WeylonSantana** [comment]
@lodicolo I saw that you added more logging information for this bug (if I understand correctly), I reproduced this bug in version 0.6.2.429
And here's the editor's log (I played it the same way as in the video, copying the "input variable" command from one event and pasting it into another.)

[errors-Intersect Editor.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5162809/errors-Intersect.Editor.log)
[Intersect Editor-2020_09_02-11_07_24_654.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5162812/Intersect.Editor-2020_09_02-11_07_24_654.log)

**Comment by lodicolo** [comment]
```
2020-09-02 14:10:01.935 [Error] Missing command list for branch 10562499-64d3-4808-a788-0bf5c17c3a78

--------------------------------------------------------------------------------
2020-09-02 14:10:02.588 [Error] 
  Message: Object reference not set to an instance of an object.
    Stack:    at Intersect.Editor.Forms.Editors.Events.CommandPrinter.PrintCommandList(EventPage page, List`1 commandList, String indent, ListBox lstEventCommands, List`1 mCommandProperties, MapInstance map) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\CommandPrinter.cs:line 47
   at Intersect.Editor.Forms.Editors.Events.CommandPrinter.PrintCommandList(EventPage page, List`1 commandList, String indent, ListBox lstEventCommands, List`1 mCommandProperties, MapInstance map) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\CommandPrinter.cs:line 196
   at Intersect.Editor.Forms.Editors.Events.CommandPrinter.PrintCommandList(EventPage page, List`1 commandList, String indent, ListBox lstEventCommands, List`1 mCommandProperties, MapInstance map) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\CommandPrinter.cs:line 132
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.ListPageCommands() in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1077
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.btnPaste_Click(Object sender, EventArgs e) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 1618
   at Intersect.Editor.Forms.Editors.Events.FrmEvent.FrmEvent_KeyDown(Object sender, KeyEventArgs e) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Events\frmEvent.cs:line 382
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


--------------------------------------------------------------------------------
```
