### ISSUE TITLE
Server does not start on the VPS, only on the personal computer.

### ISSUE THREAD

**Issue by dhmhc** [AscensionGameDev/Intersect-Engine#595]
**Describe the bug**
I'm trying to open the server on my VPS but the server opens, and closes in a moment. I've tried to disable UpNP, port checker, settings, and nothing resolves.
it seems not to be on all machines
because when I start the server on my personal computer, it starts normally.

**Version Encountered**
0.7.0.108

**To Reproduce**
Start the server clean.
The error reproduces, it seems not to be on all machines

**Expected behavior**
Open normally on any machine

**Logs**
`--------------------------------------------------------------------------------
UPnP Service Initialization Failed. You might not have a router, or UPnP on your router might be disabled.
  Message: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
    Stack:    at Open.Nat.NatDiscoverer.<DiscoverDeviceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Intersect.Server.Networking.Helpers.UpnP.<ConnectNatDevice>d__4.MoveNext() in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Server\Networking\Helpers\UPnP.cs:line 31

--------------------------------------------------------------------------------
2021-03-11 02:37:13.584 [Info] Acquiring context lock... (0ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.584 [Info] Acquired. (0ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.584 [Info] Beginning context dispose. (0ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.584 [Info] Disposing network... (2ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.584 [Info] Saving online users/players... (4ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.647 [Info] Online users/players saved. (59ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.647 [Info] Shutting down the API... (59ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.647 [Info] Base dispose. (60ms)

--------------------------------------------------------------------------------
2021-03-11 02:37:13.647 [Info] Finished disposing server context. (60ms)

--------------------------------------------------------------------------------`

**Operating System:**
Windows 10 Pro

**Comment by Cheshire92** [comment]
Could you please disable UPnP in your resources\config.json file for the server?
Should look roughly as follows:

**Comment by dhmhc** [comment]
My config: https://wtools.io/paste-code/b4gd
https://ascensiongamedev.com/resources/filehost/7385a3e3b70a57cf0e336dc15b7010d6.png

**Comment by dhmhc** [comment]
You can close this problem because it enters with problem #597 the VPS was completely buggy, nothing worked
