### ISSUE TITLE
Quest Editor - Task Editor is causing the Intersect Editor to crash due to null reference.

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#915]
**Describe the bug**
In a project that was started from prerelease around the end of May 2021, and has since been updated to the latest prerelease as of August 16th 2021, _some_ quest events can not be edited without crashing the Intersect Editor.

Some events work fine.

For others - if a Task is double clicked to edit, will get in a bad state. Clicking on "Cancel" or "Edit Completion Event" will cause the editor to crash with the following stacktrace:

```
Message: Object reference not set to an instance of an object.
    Stack:    at Intersect.Editor.Forms.Editors.Quest.QuestTaskEditor.btnEditTaskEvent_Click(Object sender, EventArgs e) in ...Intersect-Engine\Intersect.Editor\Forms\Editors\Quest\Quest_TaskEditor.cs:line 171
```

**Version Encountered**

0.7.0.0. Most recent prerelease build as of August 16th 2021. There have been minor, isolated, source edits.

**To Reproduce**
1. My guess is - have an older project that has been upgraded to current prerelease spec
2. Modify old quest tasks
3. Some will throw the error

**Expected behavior**
Am able to modify quest tasks without crashing the editor.

**Screenshots**
Looking in the source, the problem lies here:
![image](https://user-images.githubusercontent.com/8580915/129621648-c39e5738-f1ac-4005-bff3-203ecfc8e65b.png)

Or, wherever we're trying to reference `task.EditingEvent` - it's null, for some reason.

**Logs**
```
Message: Object reference not set to an instance of an object.
    Stack:    at Intersect.Editor.Forms.Editors.Quest.QuestTaskEditor.btnEditTaskEvent_Click(Object sender, EventArgs e) in ...Intersect-Engine\Intersect.Editor\Forms\Editors\Quest\Quest_TaskEditor.cs:line 171
```

**Operating System:**
Windows

**Comment by AlexVild** [comment]
Upon further digging, it seems the tasks that are broken have `QuestTask.EditingEvent` set to `null`, while events that are functional have `QuestTask.EditingEvent` set to some `EventBase()`.

Did something change with how we were storing quest tasks recently? The only thing I can think of is if previously we were okay with storing things as `null`, but now we expect them to be some empty EventBase (if there is no completion event set), then this bad state could occur.

**Comment by AlexVild** [comment]
I'm willing to share my gamedata.db with anyone who wants to help investigate

**Comment by jcsnider** [comment]
If you open your game database in Sqlite browser and go to the quests table and look at the tasks json for that quest you should find that the tasks giving you problems have 'CompletionEventIds' that are null or do not match the task 'Id'

Here is what it looks like when it's good:
```
[
    {
        "CompletionEventId": "d3b92994-d7ff-4b2d-a3b3-dfa0fcd85aa3",
        "Description": "Kill 5 shrooms in the town forest.",
        "Id": "d435e52a-900a-4635-93c5-aa0ae63f625b",
        "Objective": 2,
        "Quantity": 5,
        "TargetId": "9b19937e-114e-45bc-8a87-2adebcd2f786"
    },
    {
        "CompletionEventId": "4c075502-bb8d-4b89-a93d-d2b9ad524dcf",
        "Description": "Talk to farmer Joe to claim your reward",
        "Id": "35172655-f97b-451e-9193-57d8f30a7550",
        "Objective": 0,
        "Quantity": 0,
        "TargetId": "00000000-0000-0000-0000-000000000000"
    }
]
```

You can fix the issue by copying the 'Id' field into the 'CompletionEventId' field for now.

I need to eventually track down the cause of this bug because it is pretty rare. I assume it's a copy/paste issue but I am not for sure on that.

**Comment by AlexVild** [comment]
Ooh, a copy/paste issue is a good lead. I believe the most effected quests and tasks are ones that I heavily copy/pasted (due to them sharing completion events and/or start conditions).

Thank you very much for the fix. I will give it a go.

**Comment by AlexVild** [comment]
Just for the record, setting the CompletionID to equal the Task ID did not fix the issue :P.

**Comment by jcsnider** [comment]
In that case it is probably because an event with that id does not exist in the events table. Because it was referenced by another quest that probably got deleted. You can remove that individual task or tasks from that quest and remake them for now.

**Comment by Thomasfds** [comment]
I have same issue with event and it's on quests that we haven't touched for some time.

Could moving folder items be the result of this error?

```
--------------------------------------------------------------------------------
2021-08-29 15:41:55.085 [Warn] EditingEvent is null.

--------------------------------------------------------------------------------
2021-08-29 15:41:57.562 [Error] 
  Message: La référence d'objet n'est pas définie à une instance d'un objet.
    Stack:    à Intersect.Editor.Forms.Editors.Quest.QuestTaskEditor.btnEditTaskEvent_Click(Object sender, EventArgs e) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Quest\Quest_TaskEditor.cs:ligne 171
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à DarkUI.Controls.DarkButton.OnMouseUp(MouseEventArgs e)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------------------------------------------------------------------------
```

**Comment by Cheshire92** [comment]
I think I figured out why this is happening.. Or at least a very similar issue due to some crashes in Leafling.
Basically, what APPEARS to be happening is that on the quest task creation we are creating a task with a new Guid, then creating an EVENT for this task with **NO ID**.

When saving, the server creates a brand new event with the Task Id for the Id, then loads the actual event that **HAS NO ID** over top as instructed by the json data sent by the editor.

It then saves a lovely event with a blank Guid, or refers to a blank event and this goes.. funky.
Mind, I can't confirm this issue exists on base Intersect yet, but it does sound eerily similar and in roughly the same area, and would explain why deleting a quest task would delete other older task events.. since they all share a blank Guid for task id.

**Comment by AlexVild** [comment]
@Cheshire92 That's an exciting find. FWIW, this also crashes my editor entirely when it happens?

As always, if anyone wants to dig, I can supply my gamedata/resources and stuff

**Comment by Cheshire92** [comment]
> FWIW, this also crashes my editor entirely when it happens?

Correct, and unfortunately there doesn't appear to be an easy fix for this to fix existing errors..
Unless I manually run a bogus migration that then forces the server to go through EVERY task to generate a new event if no valid one is found, unfortunately this does mean that data that is already gone will just be.. gone.

Might need a broken DB to properly test that as a fix though.

**Comment by AlexVild** [comment]
@Cheshire92 Well reach out on discord or wherever if you need a broken DB, I got one hehe

**Comment by Cheshire92** [comment]
For anyone willing to give this a go, I've created a **POSSIBLE** fix for the issue and a migration that should attempt to relink existing events that might not be linked properly or recreate completion events in case they don't exist for quest tasks.

https://github.com/Cheshire92/Intersect-Engine/tree/Fix-915

Please for the love of god make a backup of your DB before you attempt to run that.
It might work, it might not. Has only been tested on my currently known cause and a db that I intentionally broke myself.

**Comment by Cheshire92** [comment]
According to @AlexVild the above fixes appear to resolve the issue. I'll probably turn that into a pr soon.
